# Generated by Django 6.0.7 on 2026-07-30 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def compras_a_movimientos(apps, schema_editor):
    """
    Las compras confirmadas se convierten en movimientos de entrada.

    Solo las confirmadas: un borrador nunca movio existencias, asi que
    anotarlo aqui inventaria mercancia que no llego. El stock no se toca, ya
    estaba aplicado: esto rescata el historial antes de borrar las tablas.
    """
    CompraDetalle = apps.get_model('inventario', 'CompraDetalle')
    Movimiento = apps.get_model('inventario', 'Movimiento')

    Movimiento.objects.bulk_create(
        Movimiento(
            gym_id=detalle.compra.gym_id,
            producto_id=detalle.producto_id,
            sucursal_id=detalle.compra.sucursal_id,
            tipo='entrada',
            motivo='compra',
            cantidad=detalle.cantidad,
            precio=detalle.precio,
            fecha=detalle.compra.fecha,
            usuario_id=detalle.compra.usuario_id,
            nota=(
                f'Compra #{detalle.compra_id}'
                + (f' a {detalle.compra.proveedor.nombre}'
                   if detalle.compra.proveedor_id else '')
            ),
        )
        for detalle in CompraDetalle.objects.filter(
            compra__estado='confirmada'
        ).select_related('compra', 'compra__proveedor')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_gym_whatsapp_alter_gym_telefono'),
        ('inventario', '0003_alter_compra_proveedor'),
        ('ventas', '0002_ventadetalle_membresia_alter_ventadetalle_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # El orden importa: primero la tabla nueva, luego copiar lo que habia,
        # y solo al final borrar las viejas.
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=7)),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('devolucion', 'Devolucion de un cliente'), ('venta', 'Venta'), ('merma', 'Merma'), ('ajuste', 'Ajuste de conteo')], max_length=12)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gym')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.sucursal')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
                ('venta_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='ventas.ventadetalle')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.RunPython(compras_a_movimientos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='compradetalle',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='compradetalle',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='gym',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='CompraDetalle',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
