# Generated by Django 6.0.7 on 2026-07-23 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuarios_max', models.PositiveIntegerField(default=1)),
                ('clientes_max', models.PositiveIntegerField(default=50)),
                ('sucursales_max', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gyms/logos/')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('zona_horaria', models.CharField(default='America/Mexico_City', max_length=64)),
                ('moneda', models.CharField(choices=[('MXN', 'Peso mexicano'), ('USD', 'Dolar'), ('EUR', 'Euro'), ('COP', 'Peso colombiano'), ('ARS', 'Peso argentino')], default='MXN', max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gyms', to='core.plan')),
            ],
            options={
                'verbose_name': 'Gimnasio',
                'verbose_name_plural': 'Gimnasios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.gym')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
                'unique_together': {('gym', 'nombre')},
            },
        ),
    ]
