# Generated by Django 6.0.7 on 2026-07-23 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='color_primario',
            field=models.CharField(default='#F5C518', help_text='Color de acento (botones, titulos).', max_length=7),
        ),
        migrations.AddField(
            model_name='gym',
            name='color_secundario',
            field=models.CharField(default='#111111', help_text='Color de fondo oscuro.', max_length=7),
        ),
        migrations.AddField(
            model_name='gym',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='frase_principal',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='gym',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/portadas/'),
        ),
        migrations.AddField(
            model_name='gym',
            name='sitio_publico',
            field=models.BooleanField(default=True, help_text='Muestra la pagina publica del gimnasio.'),
        ),
        migrations.AddField(
            model_name='gym',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Solo digitos con lada, ej. 5215512345678.', max_length=20),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ej. 19.432608', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ej. -99.133209', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='GymImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(upload_to='gyms/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.gym')),
            ],
            options={
                'verbose_name': 'Imagen del sitio',
                'verbose_name_plural': 'Imagenes del sitio',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
