# Generated by Django 6.0.7 on 2026-07-23 07:10

from django.db import migrations, models


def unificar_telefono(apps, schema_editor):
    """
    Ahora hay un solo numero. El de WhatsApp suele traer la lada del pais,
    asi que gana cuando el gimnasio tenia ambos.
    """
    Gym = apps.get_model('core', 'Gym')
    for gym in Gym.objects.exclude(whatsapp=''):
        gym.telefono = gym.whatsapp
        gym.save(update_fields=['telefono'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gym_color_primario_gym_color_secundario_and_more'),
    ]

    operations = [
        migrations.RunPython(unificar_telefono, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='gym',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='gym',
            name='telefono',
            field=models.CharField(blank=True, help_text='Un solo numero: sirve de contacto y de enlace a WhatsApp. Incluye la lada del pais, ej. 52 55 1234 5678.', max_length=30),
        ),
    ]
