# Generated by Django 6.0.7 on 2026-07-28 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_clientemembresia_venta_detalle'),
        ('inventario', '0003_alter_compra_proveedor'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='clientes.membresia'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='inventario.producto'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('membresia__isnull', True), ('producto__isnull', False)), models.Q(('membresia__isnull', False), ('producto__isnull', True)), _connector='OR'), name='detalle_producto_o_membresia'),
        ),
    ]
