# Generated by Django 6.0.7 on 2026-07-28 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_numeros_de_usuario'),
        ('core', '0003_remove_gym_whatsapp_alter_gym_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(help_text='El que te da BotFather al crear el bot, con el formato 123456:ABC-DEF...', max_length=100)),
                ('secreto', models.CharField(blank=True, max_length=64)),
                ('usuario_bot', models.CharField(blank=True, help_text='Nombre del bot, por ejemplo mi_gimnasio_bot.', max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='core.gym')),
            ],
            options={
                'verbose_name': 'Bot de Telegram',
                'verbose_name_plural': 'Bots de Telegram',
            },
        ),
        migrations.CreateModel(
            name='ClienteTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('nombre_telegram', models.CharField(blank=True, max_length=150)),
                ('paso', models.CharField(blank=True, max_length=30)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Socio en Telegram',
                'verbose_name_plural': 'Socios en Telegram',
            },
        ),
        migrations.CreateModel(
            name='CodigoVinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=8, unique=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_telegram', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Codigo de vinculacion',
                'verbose_name_plural': 'Codigos de vinculacion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedidaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peso_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('estatura_cm', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Medida corporal',
                'verbose_name_plural': 'Medidas corporales',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
