# Generated by Django 6.0.7 on 2026-07-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medidacorporal',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name': 'Peso registrado', 'verbose_name_plural': 'Pesos registrados'},
        ),
        migrations.RemoveField(
            model_name='medidacorporal',
            name='estatura_cm',
        ),
    ]
