# Generated by Django 6.0.7 on 2026-07-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0002_gym_color_primario_gym_color_secundario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_usuario',
            field=models.CharField(blank=True, db_index=True, help_text='Numero que teclea el cliente en el check-in. Se asigna solo.', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('gym', 'numero_usuario')},
        ),
    ]
