# Generated by Django 6.0.7 on 2026-07-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_numeros_de_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estatura_cm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='En centimetros, por ejemplo 175.', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nivel_actividad',
            field=models.CharField(blank=True, choices=[('sedentario', 'Nada o casi nada'), ('ligero', '1 a 3 dias por semana'), ('moderado', '3 a 5 dias por semana'), ('intenso', '6 o 7 dias por semana')], help_text='Cuanto entrena a la semana.', max_length=12),
        ),
    ]
