# Generated by Django 6.0.7 on 2026-07-28 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_estatura_cm_cliente_nivel_actividad'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemembresia',
            name='venta_detalle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresia_asignada', to='ventas.ventadetalle'),
        ),
    ]
