# Generated by Django 6.0.7 on 2026-07-29 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_clientemembresia_venta_detalle'),
        ('ventas', '0002_ventadetalle_membresia_alter_ventadetalle_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemembresia',
            name='venta_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias_asignadas', to='ventas.ventadetalle'),
        ),
    ]
