# Generated by Django 6.0.7 on 2026-08-01 17:39

import core.archivos
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_clientemembresia_venta_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemembresia',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Foto o PDF del pago. Opcional.', null=True, upload_to=core.archivos.RutaPorGym('comprobantes'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif', 'pdf']), core.archivos.no_pesar_de_mas]),
        ),
    ]
