# Generated by Django 6.0.7 on 2026-08-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_clientemembresia_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='foto',
            field=models.ImageField(blank=True, help_text='Se usa en la pagina publica. Sin foto la tarjeta sale solo con texto.', null=True, upload_to='membresias/'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='visible_en_sitio',
            field=models.BooleanField(default=False, help_text='Aparece en la pagina publica del gimnasio.'),
        ),
    ]
