# Generated by Django 6.0.7 on 2026-08-09 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_membresia_foto_membresia_visible_en_sitio'),
        ('core', '0003_remove_gym_whatsapp_alter_gym_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('dedo', models.CharField(choices=[('indice_der', 'Indice derecho'), ('pulgar_der', 'Pulgar derecho'), ('indice_izq', 'Indice izquierdo'), ('pulgar_izq', 'Pulgar izquierdo')], default='indice_der', max_length=12)),
                ('plantilla', models.BinaryField()),
                ('calidad', models.PositiveSmallIntegerField(default=0, help_text='Que tan buena salio la lectura, de 0 a 100.')),
                ('lector', models.CharField(blank=True, help_text='Con que lector se enrolo. Las plantillas no son compatibles entre marcas.', max_length=40)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huellas', to='clientes.cliente')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gym')),
            ],
            options={
                'verbose_name': 'Huella',
                'verbose_name_plural': 'Huellas',
                'ordering': ['cliente', 'dedo'],
                'unique_together': {('cliente', 'dedo')},
            },
        ),
    ]
