# Generated by Django 6.0.7 on 2026-08-13 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_huella'),
        ('core', '0003_remove_gym_whatsapp_alter_gym_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemembresia',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membresias_vendidas', to='core.sucursal'),
        ),
    ]
