# Generated by Django 6.0.7 on 2026-09-29 22:15

import core.archivos
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_rellenar_sucursal_de_membresias'),
        ('core', '0003_remove_gym_whatsapp_alter_gym_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoRostro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('firma', models.ImageField(help_text='El trazo que el socio hizo en la pantalla.', upload_to=core.archivos.RutaPorGym('consentimientos'))),
                ('texto', models.TextField(help_text='El aviso tal como se le enseño.')),
                ('aceptado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento_rostro', to='clientes.cliente')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gym')),
                ('usuario', models.ForeignKey(help_text='Quien lo capturo, por si despues hay que preguntarle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos_tomados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimiento de rostro',
                'verbose_name_plural': 'Consentimientos de rostro',
            },
        ),
        migrations.CreateModel(
            name='Rostro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('descriptor', models.JSONField(editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rostros', to='clientes.cliente')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gym')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rostros_enrolados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rostro',
                'verbose_name_plural': 'Rostros',
                'ordering': ['-created_at'],
            },
        ),
    ]
